name: Build & Push Docker Image

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: |
          docker build \
            -t shivalik840/rag-system:${{ github.sha }} \
            -t shivalik840/rag-system:latest .

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: github.event_name != 'pull_request'
        run: |
          docker push shivalik840/rag-system:${{ github.sha }}
          docker push shivalik840/rag-system:latest
